blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include('posts.urls', namespace="posts")),
]

posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'
urlpatterns = [
    url(r'^$', views.list_all, name='list_all'),
    url(r'^(?P<post_id>\d+)/$', views.view_post, name='view_post'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Signals #
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver
from django.core.urlresolvers import reverse
from django.core.mail import EmailMessage, EmailMultiAlternatives, send_mail
from django.contrib.sites.models import Site


class Tag(models.Model):
	text = models.CharField(max_length=64)

	def __str__(self):
		return self.text


class Post(models.Model):
	author = models.ForeignKey(User)
	tags = models.ManyToManyField(Tag, blank=True, related_name="tags")

	title = models.CharField(max_length=256)
	body_text = models.TextField()
	view_count = models.PositiveSmallIntegerField(default=0)
	
	created = models.DateTimeField(auto_now_add=True)

	def increment_view_count(self):
		self.view_count += 1;
		self.save()

	def __str__(self):
		return self.title


@receiver(post_save, sender=Post)
def post_save_blogpost(sender, instance, created, *args, **kwargs):
	""" Send an email when the post is created """
	if created:
		# Define the email data
		recipient = "adric.warth@jisc.ac.uk"
		email_from = "Django.test@example.com"
		subject = "New post: {}".format(instance.title)
		if instance.author.first_name:
			author = "{} {}".format(instance.author.first_name, instance.author.last_name)
		else:
			author = instance.username

		request = None
		relative_url = reverse('posts:view_post', args=[instance.id])
		absolute_url = ''.join(['http://', Site.objects.get_current().domain, relative_url])
		# Prepare the body content
		body_context = {
			'title': instance.title,
			'link': absolute_url,
			'author': author,
		}

		body = """
			{author} has written a new post called "{title}"
			<a href="{link}">Click here</a> to read it.
		""".format(**body_context)

		print body

		email = EmailMultiAlternatives(subject, body, email_from, [recipient])
		email.attach_alternative(body.replace('\r\n', '<br>').replace('\n', '<br>'), "text/html")
		try:
			email.send()
		except:
			pass

posts/views.py
from django.shortcuts import render
from .models import Post

# Create your views here.
def list_all(request):
	""" Displays a list of all posts """
	sort = request.GET.get('sort', 'date')
	if sort == 'date':
		order = '-created'
	else:
		order = '-view_count'

	context = {
		'posts': Post.objects.all().order_by(order)
	}
	return render(request, 'posts/list.html', context)


def view_post(request, post_id):
	""" Displays the blog post in full """

	post = Post.objects.get(id=post_id)
	post.increment_view_count()
	print post.view_count
	context = {
		'post': post,
	}
	return render(request, 'posts/view_post.html', context)

blog/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>My Blog</title>
	<style type="text/css">
		
		body{
			margin: 0;
			padding: 0;
			background-color: #EEE;
			color: #111;
			font-family: Arial;
			font-size: 13pt;
			line-height: 1.2;
		}
	</style>
</head>
<body>
	<div style="margin:1em; padding:1em; background-color:#FFE;">
		
		{% block content %}
			
		{% endblock content %}

	</div>

</body>
</html>

posts/templates/posts/list.html
{% extends "base.html" %}

{% block content %}
	
	Sort by:
	<a href="?sort=date">Newest first</a>	
	<a href="?sort=pop">Most popular first</a>	
	{% for post in posts %}
		<div style='border:1px solid #888; padding:0.5em; margin-bottom:1em;'>
			
			<h2><a href="{% url 'posts:view_post' post.id %}">{{post.title}}<a></h2>
			<em style="font-size:0.8em;">{{post.created|date:"d/m/Y"}}</em>
			<p>{{post.body_text|truncatechars:100}}</p>
		</div>
	{% endfor %}

{% endblock content %}

posts/templates/posts/view_post.html
{% extends "base.html" %}


{% block content %}
	<div style='border:1px solid #888; padding:0.5em; margin-bottom:1em;'>
		
		<h1>{{post.title}}</h1>
		<em style="font-size:0.8em;">
			Posted on {{post.created|date:"d/m/Y"}} by {{post.author.first_name}} {{post.author.last_name}}
		</em>
		<p>{{post.body_text}}</p>
		<div style="font-size:0.9em;">
			<h4>Tags</h4>
			{% for tag in post.tags.all %}
				<strong style="background-color: #CCC; padding:0.25em; margin-right:1em;">{{tag}}</strong>
			{% endfor %}
		</div>
	</div>
	<a href="{% url 'posts:list_all' %}">Back to list of posts</a>
{% endblock content %}